# Generated by Django 3.2.23 on 2023-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Default Full Name', max_length=128, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(default='Default Nick Name', max_length=128, verbose_name='Nick name'),
            preserve_default=False,
        ),
    ]
