# Generated by Django 3.2.15 on 2022-09-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_transtport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transtport',
            new_name='transport',
        ),
    ]
