version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: 'app'
    restart: 'always'
    expose:
      - '8000'
    volumes:
      - type: 'bind'
        source: './volumes/app/'
        target: '/app'
    depends_on:
      - nginx

  nginx:
    build: './nginx'
    container_name: 'nginx'
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - type: 'bind'
        source: './volumes/static'
        target: '/app/static'

      - type: 'bind'
        source: './volumes/media'
        target: '/app/media'