version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: 'app'
    restart: 'always'
    # expose:
    #   - '8000'
    ports:
      - '8000:8000'
    volumes:
      - type: 'bind'
        source: './volumes/app/'
        target: '/app'
