# Generated by Django 3.2.15 on 2022-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('name', models.CharField(max_length=255, verbose_name='Transport')),
                ('delivery', models.CharField(max_length=225, verbose_name='Delivery')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
