# Generated by Django 3.2.15 on 2022-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_alter_transport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Activate'),
            preserve_default=False,
        ),
    ]
