# Generated by Django 3.2.23 on 2023-11-29 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='merchant',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator(code='invalid_length', message='Merchant must be exactly 36 characters and like Zarinpalmerchant be', regex='.{8}\\-.{4}\\-.{4}\\-.{4}\\-.{12}')], verbose_name='Merchant'),
        ),
    ]
