# Generated by Django 3.2.15 on 2022-09-28 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_transport_activate'),
        ('orders', '0002_auto_20220918_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transtport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_transport', to='transportation.transport'),
        ),
    ]
