# Generated by Django 3.2.15 on 2023-04-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
    ]
